# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/PYTHON/PeploParser/DZ4/design.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(749, 380)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cb_obl = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_obl.sizePolicy().hasHeightForWidth())
        self.cb_obl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cb_obl.setFont(font)
        self.cb_obl.setObjectName("cb_obl")
        self.cb_obl.addItem("")
        self.cb_obl.addItem("")
        self.cb_obl.addItem("")
        self.cb_obl.addItem("")
        self.verticalLayout.addWidget(self.cb_obl)
        self.cb_obr = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_obr.sizePolicy().hasHeightForWidth())
        self.cb_obr.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cb_obr.setFont(font)
        self.cb_obr.setObjectName("cb_obr")
        self.cb_obr.addItem("")
        self.cb_obr.addItem("")
        self.cb_obr.addItem("")
        self.verticalLayout.addWidget(self.cb_obr)
        self.sb_old = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sb_old.sizePolicy().hasHeightForWidth())
        self.sb_old.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_old.setFont(font)
        self.sb_old.setObjectName("sb_old")
        self.verticalLayout.addWidget(self.sb_old)
        self.cb_opit = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_opit.sizePolicy().hasHeightForWidth())
        self.cb_opit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cb_opit.setFont(font)
        self.cb_opit.setPrefix("")
        self.cb_opit.setObjectName("cb_opit")
        self.verticalLayout.addWidget(self.cb_opit)
        self.btn_go = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_go.sizePolicy().hasHeightForWidth())
        self.btn_go.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_go.setFont(font)
        self.btn_go.setObjectName("btn_go")
        self.verticalLayout.addWidget(self.btn_go)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabGr = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabGr.sizePolicy().hasHeightForWidth())
        self.tabGr.setSizePolicy(sizePolicy)
        self.tabGr.setObjectName("tabGr")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.vl1 = QtWidgets.QVBoxLayout()
        self.vl1.setObjectName("vl1")
        self.gridLayout_2.addLayout(self.vl1, 0, 0, 1, 1)
        self.tabGr.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.vl2 = QtWidgets.QVBoxLayout()
        self.vl2.setObjectName("vl2")
        self.gridLayout_3.addLayout(self.vl2, 0, 0, 1, 1)
        self.tabGr.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.vl3 = QtWidgets.QVBoxLayout()
        self.vl3.setObjectName("vl3")
        self.gridLayout_4.addLayout(self.vl3, 0, 0, 1, 1)
        self.tabGr.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.TXT = QtWidgets.QTextEdit(self.tab_4)
        self.TXT.setMaximumSize(QtCore.QSize(16777215, 16777212))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TXT.setFont(font)
        self.TXT.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.TXT.setReadOnly(True)
        self.TXT.setObjectName("TXT")
        self.gridLayout_5.addWidget(self.TXT, 0, 0, 1, 1)
        self.tabGr.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.tabGr, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 749, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabGr.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Регрессия"))
        self.cb_obl.setItemText(0, _translate("MainWindow", "Медицина"))
        self.cb_obl.setItemText(1, _translate("MainWindow", "Транспорт и логистика"))
        self.cb_obl.setItemText(2, _translate("MainWindow", "Туризм"))
        self.cb_obl.setItemText(3, _translate("MainWindow", "IT"))
        self.cb_obr.setItemText(0, _translate("MainWindow", "Среднее"))
        self.cb_obr.setItemText(1, _translate("MainWindow", "Среднее специальное"))
        self.cb_obr.setItemText(2, _translate("MainWindow", "Высшее"))
        self.sb_old.setSuffix(_translate("MainWindow", " (возраст, лет)"))
        self.cb_opit.setSuffix(_translate("MainWindow", " (опыт работы, лет)"))
        self.btn_go.setText(_translate("MainWindow", "Запрос"))
        self.tabGr.setTabText(self.tabGr.indexOf(self.tab), _translate("MainWindow", "Возраст"))
        self.tabGr.setTabText(self.tabGr.indexOf(self.tab_2), _translate("MainWindow", "Опыт"))
        self.tabGr.setTabText(self.tabGr.indexOf(self.tab_3), _translate("MainWindow", "Образование"))
        self.TXT.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p></body></html>"))
        self.tabGr.setTabText(self.tabGr.indexOf(self.tab_4), _translate("MainWindow", "Статистика"))

